# Site settings
title: Swiss Wizard
email: katie@roachhd.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/swissy/"
url: "http://roachhd.github.io/swissy.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10
